// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VaccinationManagement.Infrastructure;

#nullable disable

namespace VaccinationManagement.Infrastructure.Migrations
{
    [DbContext(typeof(VaccinationDbContext))]
    [Migration("20250927235030_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("VaccinationManagement.Domain.Entity.Person", b =>
                {
                    b.Property<string>("Cpf")
                        .HasMaxLength(11)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Cpf");

                    b.ToTable("People", (string)null);
                });

            modelBuilder.Entity("VaccinationManagement.Domain.Entity.Vaccination", b =>
                {
                    b.Property<int>("VaccinationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Dose")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PersonCpf")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("VaccinationDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("VaccineId")
                        .HasColumnType("INTEGER");

                    b.HasKey("VaccinationId");

                    b.HasIndex("PersonCpf");

                    b.HasIndex("VaccineId");

                    b.ToTable("Vaccinations", (string)null);
                });

            modelBuilder.Entity("VaccinationManagement.Domain.Entity.Vaccine", b =>
                {
                    b.Property<int>("VaccineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("VaccineName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.HasKey("VaccineId");

                    b.ToTable("Vaccines", (string)null);
                });

            modelBuilder.Entity("VaccinationManagement.Domain.Entity.Vaccination", b =>
                {
                    b.HasOne("VaccinationManagement.Domain.Entity.Person", "Person")
                        .WithMany("Vaccinations")
                        .HasForeignKey("PersonCpf")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VaccinationManagement.Domain.Entity.Vaccine", "Vaccine")
                        .WithMany("Vaccinations")
                        .HasForeignKey("VaccineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Person");

                    b.Navigation("Vaccine");
                });

            modelBuilder.Entity("VaccinationManagement.Domain.Entity.Person", b =>
                {
                    b.Navigation("Vaccinations");
                });

            modelBuilder.Entity("VaccinationManagement.Domain.Entity.Vaccine", b =>
                {
                    b.Navigation("Vaccinations");
                });
#pragma warning restore 612, 618
        }
    }
}
